# Generated by OmopViewer 0.2.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      omopgenerics::exportSummarisedResult(data, fileName = file)
    }
  )
  
  ## output summarise_omop_snapshot -----
  ## output 17 -----
  createOutput17 <- shiny::reactive({
    result <- data |>
      filterData("summarise_omop_snapshot", input)
    OmopSketch::tableOmopSnapshot(
      result
    )
  })
  output$summarise_omop_snapshot_gt_17 <- gt::render_gt({
    createOutput17()
  })
  output$summarise_omop_snapshot_gt_17_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_omop_snapshot.", input$summarise_omop_snapshot_gt_17_download_type),
    content = function(file) {
      obj <- createOutput17()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  # summarise_characteristics -----
  
  createOutput7 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input)
    
    
    if (result |> dplyr::distinct(.data$cdm_name)|>dplyr::tally()|>dplyr::pull(n)==1) header<- NULL else header <- c("cdm_name")
    groupColumn <- c("cohort_name", "sex")
    hide <- c("table_name")
    CohortCharacteristics::tableCharacteristics(
      result,
      header = header,
      groupColumn = groupColumn,
      hide = hide, 
      type = "gt"
    )
    
  })
  
  output$summarise_characteristics_gt_7 <- gt::render_gt({
    createOutput7()
  })
  output$summarise_characteristics_gt_7_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_characteristics.", input$summarise_characteristics_gt_7_download_type),
    content = function(file) {
      createOutput7() |>
        gt::gtsave(file = file)
    }
  )
  
  ## output 8 -----
  createOutput8 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input)
    result <- result |> dplyr::filter(.data$variable_name == input$summarise_characteristics_ggplot2_8_variableName)
    if (input$summarise_characteristics_ggplot2_8_plotStyle == "densityplot"){
      plot <- visOmopResults::scatterPlot(result, 
                                          x = "density_x",
                                          y = "density_y",
                                          line = TRUE,
                                          point = FALSE,
                                          ribbon = FALSE,
                                          facet = input$summarise_characteristics_ggplot2_8_facet,
                                          colour = input$summarise_characteristics_ggplot2_8_colour)
    } else {
      plot <- CohortCharacteristics::plotCharacteristics(
        result,
        plotStyle = input$summarise_characteristics_ggplot2_8_plotStyle,
        facet = input$summarise_characteristics_ggplot2_8_facet,
        colour = input$summarise_characteristics_ggplot2_8_colour
      ) }
    plot <- plot + ggplot2::theme(axis.text.x = element_text(angle = 90, hjust = 1))
    if (input$summarise_characteristics_ggplot2_8_logscale) {
      plot <- plot + ggplot2::scale_y_log10()
    }
    
    plot
  })
  output$summarise_characteristics_ggplot2_8 <- shiny::renderPlot({
    createOutput8()
  })
  output$summarise_characteristics_ggplot2_8_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_characteristics.", "png"),
    content = function(file) {
      obj <- createOutput8()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_characteristics_ggplot2_8_download_width),
        height = as.numeric(input$summarise_characteristics_ggplot2_8_download_height),
        units = input$summarise_characteristics_ggplot2_8_download_units,
        dpi = as.numeric(input$summarise_characteristics_ggplot2_8_download_dpi)
      )
    }
  )

  # summarise_missing_data -----
  ## tidy summarise_missing_data -----
  getTidyDataSummariseMissingData <- shiny::reactive({
    res <- data |>
      filterData("summarise_missing_data", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")|>
      dplyr::mutate(estimate_value = suppressWarnings(dplyr::if_else(.data$estimate_value == "-", NA_integer_, as.numeric(.data$estimate_value))))
    
    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_missing_data_tidy_columns, "variable_name",
      "estimate_name", "estimate_value"
    )]
    
    # pivot
    pivot <- input$summarise_missing_data_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
                     "estimates" = "estimate_name",
                     "estimates and variables" = c("variable_name", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }
    
    res |>
      dplyr::select(!dplyr::any_of(colsEliminate))
  })
  output$summarise_missing_data_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseMissingData(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_missing_data_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_missing_data.csv",
    content = function(file) {
      getTidyDataSummariseMissingData() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_missing_data -----
  # output 0 -----
  createOutput26 <- shiny::reactive({
    result <- data |>
      filterData("summarise_missing_data", input)|>
      dplyr::arrange(.data$strata_level)
    
    OmopSketch::tableMissingData(result)
    
  })
  output$summarise_missing_data_gt_0 <- gt::render_gt({
    createOutput26()
  })
  output$summarise_missing_data_gt_0_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_missing_data.", input$summarise_missing_data_gt_0_download_type),
    content = function(file) {
      obj <- createOutput26()
      gt::gtsave(data = obj, filename = file)
    }
  )

  
  # summarise_concept_id_counts -----
  ## tidy summarise_concept_id_counts -----
  getTidyDataSummariseAllConceptCounts <- shiny::reactive({
    res <- data |>
      filterData("summarise_concept_id_counts", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")
    
    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_concept_id_counts_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value", ""
    )]
    
    # pivot
    pivot <- input$summarise_concept_id_counts_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
                     "estimates" = "estimate_name",
                    
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }
    
    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
    # |>
    #   dplyr::mutate(estimate_value = dplyr::if_else(.data$estimate_value!= "-", as.numeric(.data$estimate_value), NA_real_))
  })
  output$summarise_concept_id_counts_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseAllConceptCounts(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_concept_id_counts_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_concept_id_counts.csv",
    content = function(file) {
      getTidyDataSummariseAllConceptCounts() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_concept_id_counts -----
  ## output 0 -----
  createOutput27 <- shiny::reactive({
    result <- data |>
      filterData("summarise_concept_id_counts", input) |>
      dplyr::arrange(.data$variable_level, .data$additional_level)
   OmopSketch::tableConceptIdCounts(result, display = input$summarise_concept_id_counts_display)
  })
  output$summarise_concept_id_counts_gt_0 <- reactable::renderReactable({
    createOutput27()
  })
  
  output$summarise_concept_id_counts_gt_0_download <- downloadHandler(
    filename = paste0("output_reactable_summarise_concept_id_counts.", input$summarise_concept_id_counts_gt_0_download_type),
    content = function(file) {
      data <- createOutput27()
      
      # Export logic — assume input$type is "csv" or similar
      if (input$summarise_concept_id_counts_gt_0_download_type == "csv") {
        write.csv(data, file, row.names = FALSE)
      } else {
        # Optional: Save HTML widget instead of CSV (only if needed)
        htmlwidgets::saveWidget(
          widget = reactable::reactable(data),
          file = file
        )
      }
    }
  )
  
  
  
  # summarise_clinical_records -----
  ## tidy summarise_clinical_records -----
  getTidyDataSummariseClinicalRecords <- shiny::reactive({
    res <- data |>
      filterData("summarise_clinical_records", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")
    
    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_clinical_records_tidy_columns, "variable_name",
      "estimate_name", "estimate_type", "estimate_value"
    )]
    
    # pivot
    pivot <- input$summarise_clinical_records_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
                     "estimates and variables" = c("variable_name","estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }
    
    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_clinical_records_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseClinicalRecords(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_clinical_records_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_clinical_records.csv",
    content = function(file) {
      getTidyDataSummariseClinicalRecords() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_clinical_records -----
  ## output 0 -----
  # createOutput22 <- shiny::reactive({
  #   result <- data |>
  #     filterData("summarise_clinical_records", input)
  #   
  #   header <- input$summarise_clinical_records_gt_0_header
  #   group <- input$summarise_clinical_records_gt_0_group
  #   hide <- input$summarise_clinical_records_gt_0_hide
  #   
  #   if (is.null(header) || length(header) == 0) header <- c("cdm_name")
  #   if (is.null(group) || length(group) == 0) group <- c()
  #   if (is.null(hide) || length(hide) == 0) hide <- c()
  #   
  #   simpleTable(
  #     result,
  #     header = header,
  #     group = group,
  #     hide = hide
  #   )
  # })
  # output$summarise_clinical_records_gt_0 <- gt::render_gt({
  #   createOutput22()
  # })
  # output$summarise_clinical_records_gt_0_download <- shiny::downloadHandler(
  #   filename = paste0("output_gt_summarise_clinical_records.", input$summarise_clinical_records_gt_0_download_type),
  #   content = function(file) {
  #     obj <- createOutput22()
  #     gt::gtsave(data = obj, filename = file)
  #   }
  # )
  createOutput21 <- shiny::reactive({
    res <- data |>
      filterData("summarise_clinical_records", input)
    OmopSketch::tableClinicalRecords(res, type = "gt")
  })
  output$summarise_clinical_records_gt_15 <- gt::render_gt({
    
    createOutput21()
    
  })
  output$summarise_clinical_records_gt_15_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_clinical_records.", input$summarise_clinical_records_gt_15_download_type),
    content = function(file) {
      createOutput21() |>
        gt::gtsave(file = file)
    }
  )
  
  
  
  # summarise_record_count -----
  ## tidy summarise_record_count -----
  
  ## output summarise_record_count -----
  ## output 0 -----
  createOutput23 <- shiny::reactive({
    result <- data |>
      filterData("summarise_record_count", input)
    OmopSketch::tableRecordCount(result, type = "gt")
  })
  output$summarise_record_count_gt_0 <- gt::render_gt({
    createOutput23()
  })
  output$summarise_record_count_gt_0_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_record_count.", input$summarise_record_count_gt_0_download_type),
    content = function(file) {
      createOutput23()|>
        gt::gtsave(filename = file)
    }
  )
  
  createOutput18 <- shiny::reactive({
    result <- data |>
      filterData("summarise_record_count", input)
    OmopSketch::plotRecordCount(
      result,
      facet = input$summarise_record_count_ggplot2_16_facet, 
      colour = input$summarise_record_count_ggplot2_16_colour
    )
  })
  output$summarise_record_count_ggplot2_16 <- shiny::renderPlot({
    createOutput18()
  })
  output$summarise_record_count_ggplot2_16_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_record_count.", "png"),
    content = function(file) {
      obj <- createOutput18()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_record_count_ggplot2_16_download_width),
        height = as.numeric(input$summarise_record_count_ggplot2_16_download_height),
        units = input$summarise_record_count_ggplot2_16_download_units,
        dpi = as.numeric(input$summarise_record_count_ggplot2_16_download_dpi)
      )
    }
  )
  
  
  # summarise_in_observation -----
  ## tidy summarise_in_observation -----
  
  ## output summarise_in_observation -----
  ## output 0 -----
  createOutput0 <- shiny::reactive({
    result <- data |>
      filterData("summarise_in_observation", input)
    
    OmopSketch::tableInObservation(result, type = "gt")
  })
  output$summarise_in_observation_gt_0 <- gt::render_gt({
    createOutput0()
  })
  output$summarise_in_observation_gt_0_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_in_observation.", input$summarise_in_observation_gt_0_download_type),
    content = function(file) {
      createOutput0() |>
        gt::gtsave(file = file)
      
    }
  )
  
  createOutput19 <- shiny::reactive({
    result <- data |>
      filterData("summarise_in_observation", input)
    result <- result |> dplyr::filter(.data$variable_name == input$summarise_in_observation_ggplot2_19_variableName)
    print(result)
    OmopSketch::plotInObservation(
      result,
      facet = input$summarise_in_observation_ggplot2_19_facet,
      colour = input$summarise_in_observation_ggplot2_19_colour
    )
  })
  
  # Render the plot in the UI
  output$summarise_in_observation_ggplot2_19 <- shiny::renderPlot({
    createOutput19()
  })
  
  # Provide download handler for saving plot
  output$summarise_in_observation_ggplot2_19_download <- shiny::downloadHandler(
    filename = "output_ggplot2_summarise_in_observation.png",
    content = function(file) {
      obj <- createOutput19()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_in_observation_ggplot2_19_download_width),
        height = as.numeric(input$summarise_in_observation_ggplot2_19_download_height),
        units = input$summarise_in_observation_ggplot2_19_download_units,
        dpi = as.numeric(input$summarise_in_observation_ggplot2_19_download_dpi)
      )
    }
  )
  
  
  
  ## output summarise_observation_period -----
  ## output 15 -----
  createOutput15 <- shiny::reactive({
    result <- data |>
      filterData("summarise_observation_period", input)
    
    
    OmopSketch::tableObservationPeriod(
      result, 
      type = "gt"
    )
  })
  output$summarise_observation_period_gt_15 <- gt::render_gt({
    createOutput15()
  })
  output$summarise_observation_period_gt_15_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_observation_period.", input$summarise_observation_period_gt_15_download_type),
    content = function(file) {
      createOutput15() |>
        gt::gtsave(file = file)
      
    }
  )
  
  ## output 16 -----
  createOutput16 <- shiny::reactive({
    result <- data |>
      filterData("summarise_observation_period", input)
    result <- result |> dplyr::filter(.data$variable_name == input$summarise_observation_period_ggplot2_16_variableName)
    OmopSketch::plotObservationPeriod(
      result,
      variableName = input$summarise_observation_period_ggplot2_16_variableName,
      plotType = input$summarise_observation_period_ggplot2_16_plotType,
      facet = input$summarise_observation_period_ggplot2_16_facet, 
      colour = input$summarise_observation_period_ggplot2_16_colour
    )
  })
  output$summarise_observation_period_ggplot2_16 <- shiny::renderPlot({
    createOutput16()
  })
  output$summarise_observation_period_ggplot2_16_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_observation_period.", "png"),
    content = function(file) {
      obj <- createOutput16()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_observation_period_ggplot2_16_download_width),
        height = as.numeric(input$summarise_observation_period_ggplot2_16_download_height),
        units = input$summarise_observation_period_ggplot2_16_download_units,
        dpi = as.numeric(input$summarise_observation_period_ggplot2_16_download_dpi)
      )
    }
  )
}
